### ISSUE TITLE
Syntax error in the code

### ISSUE THREAD

**Issue by akononykhin** [centosadmin/redmine_telegram_common#68]
Hello

When I try to install plugin and execute the command
`bundle exec rake redmine:plugins:migrate RAILS_ENV=production`
I receive the next error:

```
rake aborted!
SyntaxError: /opt/redmine-3.2.3/plugins/redmine_telegram_common/lib/telegram_common/bot_command/start.rb:33: syntax error, unexpected '.'
...A::AuthSource::Telegram.first&.id

```
Here is information about my Redmine and Ruby versions:
```
Environment:
  Redmine version                3.2.3.stable.15582
  Ruby version                   2.2.5-p319 (2016-04-26) [x86_64-linux]
  Rails version                  4.2.5.2
  Environment                    production
  Database adapter               Mysql2

```
All looks correct for the plugin installation requirements.

What may be the reason for this error and how to fix it? 

Best regards
Alexey

**Comment by olemskoi** [comment]
Hello,

Please try to use newer version of ruby.

**Comment by funk-yourself** [comment]
Hello! Thank you for reporting this. The error is caused by safe-navigation operator (`obj&.method`) which was added in ruby 2.3.0. We apologize for this inconsistency, but ruby requirement in our Readme is outdated. Now, we support only ruby versions >= 2.3.0.
Please, note that ruby 2.2 is now only under security maintainance and its support will be completely discontinued  very soon.
